services:

    Goat\Domain\Command\DispatcherListCommand:
        public: false
        arguments: []
        tags: ["console.command"]

    Goat\Domain\Command\DispatcherPushCommand:
        public: false
        arguments: ["@goat.domain.dispatcher", "@serializer"]
        tags: ["console.command"]
