services:

    goat.domain.dispatcher:
        class: Goat\Domain\Event\DefaultDispatcher
        arguments: ['@event_dispatcher', '@messenger.bus.app', '@messenger.bus.async']
        tags: ['container.hot_path']

    goat.domain.transaction_handler.goat:
        class: Goat\Domain\Event\GoatTransactionHandler
        arguments: ['@goat.runner.default']
        tags: ['goat.domain.transaction_handler', 'container.hot_path']

    Goat\Domain\Event\Dispatcher:
        alias: goat.domain.dispatcher
