services:

    # @todo autoconfigure this from user configuration
    goat.domain.event_store.namespace_map:
        class: Goat\Domain\EventStore\NamespaceMap

    goat.domain.event_store:
        public: false
        class: Goat\Domain\EventStore\Goat\GoatEventStore
        # @todo make this configurable, allow table namespace configuration
        arguments: ["@goat.runner.default"]
        calls:
            - [setNamespaceMap, ["@goat.domain.event_store.namespace_map"]]

    # @todo this should be optional, serializer might not be present
    goat.domain.event_store.exporter:
        public: false
        class: Goat\Domain\EventStore\Exchange\EventExporter
        arguments: ['@serializer']

    Goat\Domain\EventStore\EventStore:
        public: false
        alias: goat.domain.event_store

    Goat\Domain\EventStore\Exchange\EventExporter:
        public: false
        alias: goat.domain.event_store.exporter
