goat:
    runner:
        driver: doctrine
        metadata_cache: apcu
        metadata_cache_prefix: "app_%kernel.environment%"
    query:
        enabled: true
    domain:
        enabled: true
        event_store: false
