# Journalisation services
services:

    goat.journal.goat:
        public: false
        class: Goat\Domain\Journal\GoatJournalRepository
        arguments: ['@goat.runner.default']
        tags: ['container.hot_path']

    goat.journal:
        public: true
        alias: goat.journal.goat

    Goat\Domain\Journal\Journal:
        public: true
        alias: goat.journal
