# Query builder services
services:

    goat.converter.default:
        public: false
        class: Goat\Converter\DefaultConverter
        tags: ['container.hot_path']

    Goat\Converter\ConverterInterface:
        alias: goat.converter.default
