# Query builder services
services:

    goat.converter.default:
        public: false
        class: Goat\Converter\DefaultConverter

    Goat\Converter\ConverterInterface:
        alias: goat.converter.default
