services:

    Goat\Dispatcher\Command\DispatcherListCommand:
        public: false
        arguments: ["@goat.name_map"]
        tags: ["console.command"]

    Goat\Dispatcher\Command\DispatcherPushCommand:
        public: false
        arguments: ["@goat.dispatcher", "@serializer", "@goat.name_map"]
        tags: ["console.command"]
