services:

    # Allows to maintain a different SQL connection for the projector state
    # store, allowing it to go out of business transactions scope.
    goat.runner.projector_state:
        alias: "goat.runner.default"

    goat.projector.registry:
        public: false
        class: Goat\Projector\ProjectorRegistry

    goat.projector.state_store.goat:
        public: false
        class: Goat\Projector\State\GoatStateStore
        arguments:
            - "@goat.runner.projector_state"

    goat.projector.state_store:
        alias: goat.projector.state_store.goat

    Goat\Projector\State\StateStore:
        alias: goat.projector.state_store

    goat.projector.worker:
        public: false
        class: Goat\Projector\Worker\DefaultWorker
        arguments:
            - "@goat.projector.registry"
            - "@goat.event_store"
            - "@goat.projector.state_store"

    Goat\Projector\Worker\Worker:
        alias: goat.projector.worker

    goat.projector.player:
        public: false
        class: Goat\Projector\Runtime\DefaultRuntimePlayer
        arguments:
            - "@goat.projector.registry"
            - "@goat.projector.state_store"

    Goat\Projector\Runtime\RuntimePlayer:
        alias: goat.projector.player
