services:

    Goat\Projector\Command\ProjectorListCommand:
        public: false
        arguments:
            - "@goat.projector.registry"
            - "@goat.projector.state_store"
        tags: ["console.command"]

    Goat\Projector\Command\ProjectorPlayCommand:
        public: false
        arguments:
            - "@goat.projector.registry"
            - "@goat.projector.worker"
        tags: ["console.command"]

    # @todo Temporary disabling this one, cause it crashes when
    #   symfony/messenger component is not installed.
    # Goat\MessageBroker\Command\MessageBrokerFixV2Command:
    #     public: false
    #     arguments: ["@goat.runner.default", "@goat.serializer", "@goat.name_map"]
    #     tags: ["console.command"]
