services:

    # Allows to maintain a different SQL connection for the projector state
    # store, allowing it to go out of business transactions scope.
    goat.runner.projector_state:
        alias: "goat.runner.default"

    goat.projector_registry:
        public: false
        class: Goat\Projector\ProjectorRegistry

    goat.projector_state_store.goat:
        public: false
        class: Goat\Projector\State\GoatStateStore
        arguments:
            - "@goat.runner.projector_state"

    goat.projector_state_store:
        alias: goat.projector_state_store.goat

    Goat\Projector\State\StateStore:
        alias: goat.projector_state_store

    goat.projector_worker:
        public: false
        class: Goat\Projector\Worker\DefaultWorker
        arguments:
            - "@goat.projector_registry"
            - "@goat.event_store"
            - "@goat.projector_state_store"

    Goat\Projector\Worker\Worker:
        alias: goat.projector_worker

    goat.projector_player:
        public: false
        class: Goat\Projector\Runtime\DefaultRuntimePlayer
        arguments:
            - "@goat.projector_registry"
            - "@goat.projector_state_store"

    Goat\Projector\Runtime\RuntimePlayer:
        alias: goat.projector_player
