services:

    # Symfony 4.2: this service is not aliased with its interface.
    Symfony\Component\Messenger\Handler\HandlersLocatorInterface:
        alias: messenger.bus.sync.messenger.handlers_locator

    goat.domain.dispatcher:
        public: false
        class: Goat\Domain\Event\DefaultDispatcher
        arguments: ['@messenger.bus.sync.messenger.handlers_locator', '@goat.domain.message_broker']
        tags: [{ name: "monolog.logger", channel: "goat_dispatcher" }]

    goat.domain.dispatcher_middleware:
        public: false
        class: Goat\Domain\Messenger\DispatcherMiddleware
        arguments: ['@goat.domain.dispatcher']

    goat.domain.transaction_handler.goat:
        public: false
        class: Goat\Domain\Event\GoatTransactionHandler
        arguments: ['@goat.runner.default']
        tags: [{ name: "goat.domain.transaction_handler" }]

    Goat\Domain\Event\Dispatcher:
        public: true
        alias: goat.domain.dispatcher
