services:

    Goat\Domain\Command\DispatcherListCommand:
        public: false
        arguments: ["@goat.domain.name_map"]
        tags: ["console.command"]

    Goat\Domain\Command\DispatcherPushCommand:
        public: false
        arguments: ["@goat.domain.dispatcher", "@serializer", "@goat.domain.name_map"]
        tags: ["console.command"]
