services:

    Goat\Projector\Command\ProjectorListCommand:
        public: false
        arguments:
            - "@goat.projector.registry"
            - "@goat.projector.state_store"
        tags: ["console.command"]

    Goat\Projector\Command\ProjectorPlayCommand:
        public: false
        arguments:
            - "@goat.projector.registry"
            - "@goat.projector.worker"
        tags: ["console.command"]
