services:

    Goat\Bridge\Symfony\Messenger\Transport\PgSQLTransportFactory:
        public: false
        arguments: ["@goat.domain.message_broker"]
        tags: [{ name: "messenger.transport_factory" }]
