services:

    Goat\Bridge\Symfony\Messenger\Transport\PgSQLTransportFactory:
        public: false
        arguments: ["@goat.runner.default", "@?messenger.transport.serializer", "%kernel.debug%", "%kernel.environment%"]
        tags: [messenger.transport_factory]
