services:

    Goat\Bridge\Symfony\Messenger\Transport\PgSQLTransportFactory:
        public: false
        arguments: ["@goat.runner.default", "%kernel.debug%", "%kernel.environment%"]
        tags: [messenger.transport_factory]
