services:

    goat.name_map:
        public: false
        class: Goat\Normalization\DefaultNameMap
        arguments: [[], []]

    Goat\Normalization\NameMap:
        public: false
        alias: goat.name_map

    Goat\Normalization\TypeMap:
        public: false
        alias: goat.name_map
