services:

    goat.serializer:
        public: false
        class: Goat\Bridge\Symfony\Serializer\GoatSerializerAdapter
        arguments: ["@?serializer"]

    goat.name_map.strategy.prefix:
        public: false
        class: Goat\Normalization\PrefixNameMappingStrategy
        arguments: ['App', 'App'] # Filled later by extension.

    goat.name_map.strategy.default:
        alias: goat.name_map.strategy.prefix

    goat.name_map:
        public: false
        class: Goat\Normalization\DefaultNameMap
        arguments: ['@goat.name_map.strategy.default']

    Goat\Normalization\NameMap:
        public: false
        alias: goat.name_map

    Goat\Normalization\Serializer:
        public: false
        alias: goat.serializer
