services:

    goat.serializer:
        public: false
        class: Goat\Bridge\Symfony\Serializer\GoatSerializerAdapter
        arguments: ["@serializer"]

    goat.name_map:
        class: Goat\Normalization\DefaultNameMap
        public: false

    Goat\Normalization\NameMap:
        public: false
        alias: goat.name_map

    Goat\Normalization\Serializer:
        public: false
        alias: goat.serializer
