services:

    goat.preferences.handler:
        public: false
        class: Goat\Preferences\Domain\Handler\PreferencesHandler
        arguments: ['@goat.preferences.repository', '@?goat.preferences.schema']
        tags: ['messenger.message_handler']
